import { createToolIdentityIcon } from '@/components/icons';
import type { ToolDefinition } from '@/types/tools';

export const TOOLS: readonly ToolDefinition[] = [
  {
    id: 'merge',
    slug: 'merge',
    name: 'Merge PDF',
    description: 'Combine multiple PDF documents into a single, cohesive file in your chosen order.',
    shortDescription: 'Combine multiple PDFs into one.',
    iconName: 'Files',
    icon: createToolIdentityIcon('merge'),
    category: 'organize',
    badge: 'Popular',
    popular: true,
  },
  {
    id: 'split',
    slug: 'split',
    name: 'Split PDF',
    description: 'Extract specific page ranges or split each page into standalone documents.',
    shortDescription: 'Extract pages or split into standalone files.',
    iconName: 'Scissors',
    icon: createToolIdentityIcon('split'),
    category: 'organize',
    badge: 'Popular',
    popular: true,
  },
  {
    id: 'reorder',
    slug: 'reorder',
    name: 'Reorder PDF',
    description: 'Reorganize page flow, swap positions, and clean up multi-page documents.',
    shortDescription: 'Reorganize and reorder pages in your document.',
    iconName: 'ArrowsDownUp',
    icon: createToolIdentityIcon('reorder'),
    category: 'organize',
  },
  {
    id: 'rotate',
    slug: 'rotate',
    name: 'Rotate PDF',
    description: 'Fix page orientations permanently by rotating 90, 180, or 270 degrees.',
    shortDescription: 'Rotate pages clockwise or counter-clockwise.',
    iconName: 'ArrowsClockwise',
    icon: createToolIdentityIcon('rotate'),
    category: 'organize',
  },
  {
    id: 'remove-pages',
    slug: 'remove-pages',
    name: 'Remove Pages',
    description: 'Delete unnecessary or sensitive pages from your document while keeping the rest intact.',
    shortDescription: 'Delete specific pages from your document.',
    iconName: 'FileMinus',
    icon: createToolIdentityIcon('remove-pages'),
    category: 'organize',
    badge: 'New',
  },
  {
    id: 'extract',
    slug: 'extract',
    name: 'Extract Pages',
    description: 'Extract individual pages or custom ranges into a fresh, standalone PDF document.',
    shortDescription: 'Extract selected pages into a standalone PDF.',
    iconName: 'Export',
    icon: createToolIdentityIcon('extract'),
    category: 'organize',
    badge: 'New',
  },
  {
    id: 'images-to-pdf',
    slug: 'images-to-pdf',
    name: 'Images to PDF',
    description: 'Convert JPG, PNG, and WebP images into a standardized, shareable PDF document.',
    shortDescription: 'Turn images into a single PDF.',
    iconName: 'FileImage',
    icon: createToolIdentityIcon('images-to-pdf'),
    category: 'convert',
    badge: 'Popular',
    popular: true,
  },
  {
    id: 'pdf-to-images',
    slug: 'pdf-to-images',
    name: 'PDF to Images',
    description: 'Render high-resolution PNG or JPG image extracts from any PDF document.',
    shortDescription: 'Convert PDF pages into images.',
    iconName: 'Image',
    icon: createToolIdentityIcon('pdf-to-images'),
    category: 'convert',
    badge: 'New',
    popular: true,
  },
  {
    id: 'pdf-to-markdown',
    slug: 'pdf-to-markdown',
    name: 'PDF to Markdown',
    description: 'Extract text content from your PDF documents into clean, structured Markdown format.',
    shortDescription: 'Extract formatted text from PDF to Markdown.',
    iconName: 'FileCode',
    icon: createToolIdentityIcon('pdf-to-markdown'),
    category: 'convert',
    badge: 'New',
  },
  {
    id: 'page-numbers',
    slug: 'page-numbers',
    name: 'Add Page Numbers',
    description: 'Insert customizable page numbers, position headers or footers, and set starting values.',
    shortDescription: 'Add page numbers with custom positioning.',
    iconName: 'ListNumbers',
    icon: createToolIdentityIcon('page-numbers'),
    category: 'edit',
    badge: 'New',
  },
  {
    id: 'watermark',
    slug: 'watermark',
    name: 'Watermark',
    description: 'Apply semi-transparent text stamps or confidentiality markers across your document pages.',
    shortDescription: 'Apply custom text watermarks across pages.',
    iconName: 'Stamp',
    icon: createToolIdentityIcon('watermark'),
    category: 'edit',
    badge: 'New',
  },
  {
    id: 'crop',
    slug: 'crop',
    name: 'Crop PDF',
    description: 'Trim page margins and adjust visible viewport areas across document pages.',
    shortDescription: 'Trim page margins and visible areas.',
    iconName: 'Crop',
    icon: createToolIdentityIcon('crop'),
    category: 'edit',
    badge: 'New',
  },
  {
    id: 'sign',
    slug: 'sign',
    name: 'Sign PDF',
    description: 'Draw, place, and size a visual signature directly onto any page of your document.',
    shortDescription: 'Draw and place signatures directly on pages.',
    iconName: 'Signature',
    icon: createToolIdentityIcon('sign'),
    category: 'edit',
    badge: 'New',
  },
  {
    id: 'compress',
    slug: 'compress',
    name: 'Compress PDF',
    description: 'Reduce document file sizes to simplify sharing while preserving readability.',
    shortDescription: 'Reduce PDF file size while keeping quality.',
    iconName: 'ArrowsIn',
    icon: createToolIdentityIcon('compress'),
    category: 'optimize',
    badge: 'Popular',
    popular: true,
  },
  {
    id: 'protect',
    slug: 'protect',
    name: 'Protect PDF',
    description: 'Password-protect your PDF with AES-256 encryption or unlock protected documents.',
    shortDescription: 'Password-protect or remove protection from a PDF.',
    iconName: 'ShieldCheck',
    icon: createToolIdentityIcon('protect'),
    category: 'security',
    badge: 'New',
  },
] as const;

export const POPULAR_TOOL_IDS = [
  'images-to-pdf',
  'pdf-to-images',
  'merge',
  'compress',
  'split',
  'sign',
] as const;

export const TOOL_MAP: Readonly<Record<string, ToolDefinition>> = TOOLS.reduce<
  Record<string, ToolDefinition>
>((acc, tool) => {
  acc[tool.slug] = tool;
  return acc;
}, {});
