import {
  Layers,
  Scissors,
  ArrowUpDown,
  RotateCw,
  Images,
  Minimize2,
  FileImage,
  FileMinus,
  FileOutput,
  Hash,
  Stamp,
  Crop,
  FileCode,
  PenTool,
  ShieldCheck,
} from 'lucide-react';
import type { ToolDefinition } from '@/types/tools';

export const TOOLS: readonly ToolDefinition[] = [
  {
    id: 'merge',
    slug: 'merge',
    name: 'Merge PDF',
    description: 'Combine multiple PDF documents into a single, cohesive file in your chosen order.',
    shortDescription: 'Combine multiple PDFs into one.',
    iconName: 'Layers',
    icon: Layers,
    category: 'organize',
    badge: 'Popular',
    popular: true,
  },
  {
    id: 'split',
    slug: 'split',
    name: 'Split PDF',
    description: 'Extract specific page ranges or split each page into standalone documents.',
    shortDescription: 'Extract pages or split into standalone files.',
    iconName: 'Scissors',
    icon: Scissors,
    category: 'organize',
    badge: 'Popular',
    popular: true,
  },
  {
    id: 'reorder',
    slug: 'reorder',
    name: 'Reorder PDF',
    description: 'Reorganize page flow, swap positions, and clean up multi-page documents.',
    shortDescription: 'Reorganize and reorder pages in your document.',
    iconName: 'ArrowUpDown',
    icon: ArrowUpDown,
    category: 'organize',
  },
  {
    id: 'rotate',
    slug: 'rotate',
    name: 'Rotate PDF',
    description: 'Fix page orientations permanently by rotating 90, 180, or 270 degrees.',
    shortDescription: 'Rotate pages clockwise or counter-clockwise.',
    iconName: 'RotateCw',
    icon: RotateCw,
    category: 'organize',
  },
  {
    id: 'remove-pages',
    slug: 'remove-pages',
    name: 'Remove Pages',
    description: 'Delete unnecessary or sensitive pages from your document while keeping the rest intact.',
    shortDescription: 'Delete specific pages from your document.',
    iconName: 'FileMinus',
    icon: FileMinus,
    category: 'organize',
    badge: 'New',
  },
  {
    id: 'extract',
    slug: 'extract',
    name: 'Extract Pages',
    description: 'Extract individual pages or custom ranges into a fresh, standalone PDF document.',
    shortDescription: 'Extract selected pages into a standalone PDF.',
    iconName: 'FileOutput',
    icon: FileOutput,
    category: 'organize',
    badge: 'New',
  },
  {
    id: 'images-to-pdf',
    slug: 'images-to-pdf',
    name: 'Images to PDF',
    description: 'Convert JPG, PNG, and WebP images into a standardized, shareable PDF document.',
    shortDescription: 'Convert JPG, PNG, and WebP images to PDF.',
    iconName: 'Images',
    icon: Images,
    category: 'convert',
    badge: 'Popular',
    popular: true,
  },
  {
    id: 'pdf-to-images',
    slug: 'pdf-to-images',
    name: 'PDF to Images',
    description: 'Render high-resolution PNG or JPG image extracts from any PDF document.',
    shortDescription: 'Convert PDF pages to PNG or JPG images.',
    iconName: 'FileImage',
    icon: FileImage,
    category: 'convert',
    badge: 'New',
    popular: true,
  },
  {
    id: 'pdf-to-markdown',
    slug: 'pdf-to-markdown',
    name: 'PDF to Markdown',
    description: 'Extract text content from your PDF documents into clean, structured Markdown format.',
    shortDescription: 'Extract formatted text from PDF to Markdown.',
    iconName: 'FileCode',
    icon: FileCode,
    category: 'convert',
    badge: 'New',
  },
  {
    id: 'page-numbers',
    slug: 'page-numbers',
    name: 'Add Page Numbers',
    description: 'Insert customizable page numbers, position headers or footers, and set starting values.',
    shortDescription: 'Add page numbers with custom positioning.',
    iconName: 'Hash',
    icon: Hash,
    category: 'edit',
    badge: 'New',
  },
  {
    id: 'watermark',
    slug: 'watermark',
    name: 'Watermark',
    description: 'Apply semi-transparent text stamps or confidentiality markers across your document pages.',
    shortDescription: 'Apply custom text watermarks across pages.',
    iconName: 'Stamp',
    icon: Stamp,
    category: 'edit',
    badge: 'New',
  },
  {
    id: 'crop',
    slug: 'crop',
    name: 'Crop PDF',
    description: 'Trim page margins and adjust visible viewport areas across document pages.',
    shortDescription: 'Trim page margins and visible areas.',
    iconName: 'Crop',
    icon: Crop,
    category: 'edit',
    badge: 'New',
  },
  {
    id: 'sign',
    slug: 'sign',
    name: 'Sign PDF',
    description: 'Draw, place, and size a visual signature directly onto any page of your document.',
    shortDescription: 'Draw and place signatures directly on pages.',
    iconName: 'PenTool',
    icon: PenTool,
    category: 'edit',
    badge: 'New',
  },
  {
    id: 'compress',
    slug: 'compress',
    name: 'Compress PDF',
    description: 'Reduce document file sizes to simplify sharing while preserving readability.',
    shortDescription: 'Reduce PDF file size while keeping quality.',
    iconName: 'Minimize2',
    icon: Minimize2,
    category: 'optimize',
    badge: 'Popular',
    popular: true,
  },
  {
    id: 'protect',
    slug: 'protect',
    name: 'Protect PDF',
    description: 'Password-protect your PDF with AES-256 encryption or unlock protected documents.',
    shortDescription: 'Password-protect or remove protection from a PDF.',
    iconName: 'ShieldCheck',
    icon: ShieldCheck,
    category: 'security',
    badge: 'New',
  },
] as const;

export const POPULAR_TOOL_IDS = [
  'merge',
  'split',
  'compress',
  'reorder',
  'rotate',
  'sign',
] as const;

export const TOOL_MAP: Readonly<Record<string, ToolDefinition>> = TOOLS.reduce<
  Record<string, ToolDefinition>
>((acc, tool) => {
  acc[tool.slug] = tool;
  return acc;
}, {});
